### ISSUE TITLE
zone creation copies publisher properties, but not approved CA certificates

### ISSUE THREAD

**Issue by lotheac** [omniti-labs/pkg5#2]
In the global zone, I use a publisher with signature-policy=require-signatures
and a per-publisher certificate (with set-publisher --approve-ca-cert). When I
install a new pkg-brand zone, this publisher and the signature-policy get
copied to the ngz's pkg image, but installing anything from the publisher
fails because the approved CA certificate is not copied.

**Comment by danmcd** [comment]
A solution is likely going to have to alter this:

https://github.com/omniti-labs/pkg5/blob/omnios/src/brand/attach

I'm at Surge this week, so cycles are small, but this is where the signature policy gets copied.

**Comment by lotheac** [comment]
There's also this: https://github.com/omniti-labs/pkg5/blob/omnios/src/brand/pkgcreatezone

I'll look at this sometime later, just making a note of it here.

**Comment by lotheac** [comment]
I ended up creating a new private pkg(1) subcommand to copy publishers from one image to another. It still needs testing but the diffstat so far looks promising:

```
commit d3574a98a6cb2c123e07dd8097facfd21c7fc4cf
Author: Lauri Tirkkonen <lotheac@iki.fi>
Date:   Thu Dec 31 15:30:26 2015 +0200

    wip: copy-publishers-from

 src/brand/attach        | 264 +----------------------------------------------
 src/brand/pkgcreatezone | 334 ++++++++----------------------------------------------------
 src/client.py           |  21 ++++
 3 files changed, 66 insertions(+), 553 deletions(-)
```

I'll follow up next year :)
